### PR TITLE
[*] Update to Minecraft 1.19.4

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
This is able to compile and for basic gameplay. Anything further has not yet been stress-tested.

### CODE REVIEW

**Comment by Slooshie1** [comment]
image

**Comment by ThexXTURBOXx** [comment]
@Slooshie1 You need to assign more RAM (Java heap space)

**Comment by Siphalor** [comment]
Hey and thanks for the work!
I rebased your PR on the `v4-unstable` branch as that was already on 1.19.3 and contained some of the necessary changes.
I'm testing the functionality now and will then proceed to merge the PR.

**Review by Siphalor — APPROVED** [review]
Looking good now.
Thanks again :)

**Comment by ThexXTURBOXx** [comment]
@Siphalor Thank you very much for merging the PR! Currently, I am not at home, so I cannot work on mouse-wheelie right now.
If you want, you can work on it. Otherwise, I might do it in a few days

**Comment by Siphalor** [comment]
I'll have a go at updating Mouse Wheelie tonight based on your PR over there.
I am the one to thank you ^^

**Comment by ThexXTURBOXx** [comment]
Good luck and you're more than welcome! :)

**Pull request merged**
